web:
  # Build the Drupal 8 image
  # https://hub.docker.com/r/_/drupal/
  #image: drupal:8.2.0-rc1-apache
  # Environment variables
  build: .
  environment:
    # Drupal settings
    DRUPAL_PROFILE: standard
    DRUPAL_SITE_NAME: Drupal
    DRUPAL_USER: admin
    DRUPAL_PASS: 1965
    DRUPAL_DBURL: mysql://drupal:drupal@database:3306/drupal
    XDEBUG_CONFIG: "remote_host=188.0.67.76"
    PHP_IDE_CONFIG: "serverName=dr8serv"
  ports:
    # Host machine's port 8000 will map to Drupal's port 80
    - "8080:80"
  volumes:
    # Drupal should live in the "drupal" directory
    - /var/www/drupal8:/var/www/html
    - logs:/var/log/apache2
#    - /etc/php/7.0/apache2/php.ini:/usr/local/etc/php/php.ini

  links:
    - database:database
#  command: php -S 0.0.0.0:80 -t /app
  working_dir: /var/www/html
  restart: always

# MySQL Server
database:
  hostname: mysql
  image: mysql
  environment:
    MYSQL_USER: root
    MYSQL_PASSWORD: 1965
    MYSQL_DATABASE: drupal
    MYSQL_ROOT_PASSWORD: '1965'
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  restart: always

#composer:
#  image: louisbl/composer
